'*.{ts,tsx,js}':
  - 'cmd /c pnpm exec eslint --cache --cache-location ./node_modules/.cache/eslintcache --fix'
  - 'prettier --loglevel warn --cache --write'
'*.{json,yml,scss}': 'prettier --loglevel warn --cache --write'
